/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/**
 *  TODO
 *  Create endpoint on server to fetch this file for CI instead.
 */

export interface paths {
    "/event_server": {
        parameters: {
            query: {
                /** @description a */
                operation: string;
                /** @description a */
                table: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * a
         * @description a
         */
        get: operations["event_server"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_server: {
        parameters: {
            query: {
                /** @description a */
                operation: string;
                /** @description a */
                table: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event_key?: string;
                        id?: string;
                        required?: boolean;
                        event_property_data_type?: string;
                        number_value_minimum?: string;
                        number_value_maximum?: string;
                        string_length_maximum?: string;
                        regular_expression_match?: string;
                        version?: number;
                        event_property_key?: string;
                    };
                };
            };
        };
    };
}
